### ISSUE TITLE
Footer overlays content

### ISSUE THREAD

**Issue by ericjanto** [lysts/lysts.github.io#3]
## Issue
The footer overlays the end of an article, and the user is not able to scroll further up to reveal it:

<img width="1014" alt="image" src="https://github.com/lysts/lysts.github.io/assets/55640281/93cfeca1-99c6-43d4-927b-91f422bbd2a3">

## How to resolve
Two ways:
- either un-fix the position of the footer so that it's actually positioned after the article content (I assume you want to it be visible at all times, though. It's a nice layout.)
- or add an additional 'empty' element at the end of the article which has the height of the footer and allows the user to scroll the content into view all the way.

**Comment by lysts** [comment]
so you can't add padding to resolve the issue?

**Comment by ericjanto** [comment]
> so you can't add padding to resolve the issue?

ah yes, padding or margin would solve it too. Sometimes I forget how css works oops

**Comment by lysts** [comment]
tweaked a wee bit, lmk what you think

**Comment by ericjanto** [comment]
yup, your fix works on my end
